name: moviesapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_auth_buttons:
  firebase_auth: ^0.16.0
  google_sign_in:
  cloud_firestore:
  firebase_analytics: ^5.0.6
  firebase_core: ^0.4.2+1
  material_design_icons_flutter: ^4.0.5245
  shared_preferences:
  image_picker: ^0.6.6+4
  email_validator: 1.0.4
  curved_navigation_bar: ^0.3.2
  http: 0.12.0+4
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^2.2.0+1
  path_provider: ^1.6.9
  image: ^2.1.13
  uuid: ^2.0.4
  firebase_storage: ^3.1.6
  url_launcher:
  flutter_rating: ^0.0.2
  like_button: ^0.2.0
  flutter_swiper: ^1.1.6
  splashscreen: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
